### ISSUE TITLE
error parsing output

### ISSUE THREAD

**Issue by vanillagranilla** [massimocode/amazon-ses-notification-processor#2]
`npm run fetch` runs successfully and I can see the messages in output.json.  When I run `npm run parse` all the messages get marked as errors as follows:

```
{ message: 'Cannot read property \'complainedRecipients\' of undefined',
  stack: 'TypeError: Cannot read property \'complainedRecipients\' of undefined\n    at ComplaintProcessor.processNotification (/Users/username/git/amazon-ses-notification-processor/lib/complaint-processor.js:9:44)\n    at Consumer.create.handleMessage.error [as handleMessage] (/Users/username/git/amazon-ses-notification-processor/lib/base-processor.js:22:26)\n    at handleMessage (/Users/username/git/amazon-ses-notification-processor/node_modules/sqs-consumer/index.js:148:16)\n    at
  /Users/username/git/amazon-ses-notification-processor/node_modules/async/lib/async.js:607:21\n    at /Users/username/git/amazon-ses-notification-processor/node_modules/async/lib/async.js:246:17\n    at iterate (/Users/username/git/amazon-ses-notification-processor/node_modules/async/lib/async.js:146:13)\n    at async.eachSeries (/Users/username/git/amazon-ses-notification-processor/node_modules/async/lib/async.js:162:9)\n    at _asyncMap
  (/Users/username/git/amazon-ses-notification-processor/node_modules/async/lib/async.js:245:13)\n    at Object.mapSeries (/Users/username/git/amazon-ses-notification-processor/node_modules/async/lib/async.js:228:23)\n    at Object.async.series (/Users/username/git/amazon-ses-notification-processor/node_modules/async/lib/async.js:605:19)' }
```

**Comment by vanillagranilla** [comment]
This may be because I was trying to use the same queue for bounces and complaints.  Testing now.
